import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi_web/sqflite_ffi_web.dart';

/// Web platform. Uses the WASM-backed sqflite factory (data persists in the
/// browser via IndexedDB). Requires the WASM assets generated by
/// `dart run sqflite_common_ffi_web:setup` to be present in `web/`.
void initDatabaseFactory() {
  databaseFactory = databaseFactoryFfiWeb;
}
